### ISSUE TITLE
Pinned LibreOffice icon in IconTasklist disappears when opening a document

### ISSUE THREAD

**Issue by Patrice84** [BuddiesOfBudgie/budgie-desktop#107]
## Description

Hi all,
Since last Solus update, 17 of March 22, I noticed a strange behaviour of LibreOffice icon in top panel.
I am using the Budgie desktop.
LibreOffice is iconify (marked with a star) on the Top panel, and that's what I am using to start it.
After starting Solus, icon is there and I can start LibreOffice by clicking the icon. Then, if I open a document (.odt in my case), the pinned icon disappear.
The icon that appears normally with a blue bar on top (LibreOffice writer in my case), disappear as well. But I can continue to work.
Then, LibreOffice closes normally. It's just the icon on my top panel that is not there anymore.
If I open LibreOffice from the top left menu, LibreOffice starts, but no icon appears anywhere. If I then open a document (.odt for instance), the LibreOffice writer icon appears,
until I close the document and come back to the start page of LibreOffice. But, then no icon appears anywhere.
I can still work with LibreOffice, but I think this might be a bug coming with the Budgie update.
Update : at the time I wrote this, it was Budgie 10.6, it's now 10.6.1
Going to the Budgie settings, clicking on Icon task bar, then grouping window make the icon to reappear.

## Budgie version
 Budgie 10.6.1

## Operating system
 Solus 4.3

## Steps to reproduce the issue

Please see the movie with the link below.

## Actual result

https://u.pcloud.link/publink/show?code=XZvM4JVZO8KyNMY63HXRsnbw2nFUEzW1LtiX

**Comment by serebit** [comment]
I've changed the title to one that better describes the issue you're seeing. "Budgie weird behavior" is technically accurate to what you're describing, but it's better to concisely detail exactly what you're seeing in the title. On the other hand, you've given a great amount of detail in the issue itself, so thank you very much for that—we'll see what we can do.

**Comment by serebit** [comment]
Happens on my system as well, latest git master on EndeavourOS.

**Comment by serebit** [comment]
This goes pretty deep. Ultimately, the reason the LibreOffice starter icon gets removed is because of this snippet in `src/applets/icon-tasklist/IconTasklistApplet`:

```vala
ButtonWrapper wrapper = (button.get_parent() as ButtonWrapper);
if (wrapper == null) {
    return;
}

wrapper.gracefully_die();

this.remove_button(window.get_xid().to_string());
this.on_app_opened(app);
```

Somehow, the `wrapper.gracefully_die()` function is called, which removes the starter app from the list. The callback shouldn't even get to that point, but LibreOffice does some wonky things with class groups. This isn't the first time LibreOffice has caused an issue with our window tracking, and I doubt it'll be the last.

**Comment by akyag** [comment]
I have maybe a related issue as well. Since 10.6.1, no taskbar icon shows up when I launch mpv. I am on EndeavourOS. I had mpv pinned, so clicking on it would launch mpv but the window would have no connection to the taskbar icon.. Clicking on it would start another instance and not minimize or bring to front the exisiting instance. When I unpinned mpv from taskbar it no longer appears now. 

I have tried resetting the budgie-panel and the problem persists.

**Comment by JoshStrobl** [comment]
I would recommend trying budgie-desktop-git from the AUR and seeing if that sorts it.

**Comment by akyag** [comment]
Just tried it. Installed: 10.6.r37.g14b685bf-1 but the problem still persists.

**Comment by JoshStrobl** [comment]
> Just tried it. Installed: 10.6.r37.g14b685bf-1 but the problem still persists.

#105 is likely closer to your issue than this is.
