### ISSUE TITLE
Unable to build project on Ubuntu

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/budgie-desktop#12]
## Description
The project cannot be built on the latest stable version of Ubuntu - 21.10 due to Mutter 8 support having been removed from the repo as part of the Mutter 9 - GNOME 41 update.  

I do support the idea that there is no need to support the last LTS - developers should be using the latest stable/development release for git master type development.

Unfortunately also, the current 22.04 development distro, git master cannot be built because of similar reasons.

Looks very much the project was a little overzealous with the tidyup of supported versions.
Suggestion/Request here is to readd back Mutter 8 support (I will look at this) to allow Ubuntu devs to build and develop against - at least until GNOME 42 lands.  There is no guarantee at this stage that 22.04 LTS will have GNOME 42.  Expect to see some discussion about this before Ubuntu freeze dates end of feb.

## Budgie version
10.5.3 - git master

## Operating system
Ubuntu stable 21.10 / Ubuntu development 22.04

## Steps to reproduce the issue
usual git clone/meson/ninja etc

## Actual result
dependency checks in meson prevent meson configure

## Expected result
meson build and install works as normal for the latest stable release.

**Comment by JoshStrobl** [comment]
Yea we'll have to keep a close eye on how scalable it is to support "latest stable" for Ubuntu going forward, especially since as you said it's up in the air on whether or not they're going to adopt latest stack. I don't really have any insight on their decision making process as to why / when they opt to not upgrade specific components, I just don't want us being put in a position of supporting too old of a GNOME Stack when the rest of the ecosystem has moved forward.

All that said, reintroducing Mutter 8 support is fine by me.
