### ISSUE TITLE
Budgie desktop spamming syslog with warnings

### ISSUE THREAD

**Issue by tunnnas** [BuddiesOfBudgie/budgie-desktop#137]
hi! i tend to not file issues, so, i might not express myself clearly or add needed details, if so, im sorry:(

my Syslog is full of this:

budgie-panel.desktop[6418]: #033[1;33mWarning:#033[0m choose a number between 1 to 5

Syslog is very heavy right now, up to 65G

i dont know what to do. im just tryna to configure Logrotate to mitigate the problem

**Comment by serebit** [comment]
After looking into this, it seems likely that this is an issue with an application you're running within Budgie, and not with Budgie itself. I can't seem to find an instance of that log message anywhere in Budgie, or within GTK - admittedly I haven't looked everywhere, but the warning you've included also isn't formatted the way Vala warning messages are typically formatted.

In the time since you've submitted this issue, have you figured out anything else about this, or managed to mitigate the problem?

**Comment by JoshStrobl** [comment]
Yes this is an issue with a specific application. When Budgie launches an application it ends up with the logs as a result of how the process is being created. Potentially something we can remedy but that is out of scope of this issue.
