### ISSUE TITLE
budgie-panel 10.6.1 memory usage high

### ISSUE THREAD

**Issue by fugo** [BuddiesOfBudgie/budgie-desktop#150]
After update budgie-panel 10.6.1 increase the use of RAM
After a short while over 1GB up to 3GB and more.
If I open telegram-desktop it happens faster.

RAM 8GB
Arch Linux with budgie-wm

First i thought it's the weather app but no change without that.
I use adementary-dark theme, should I try another theme?

**Comment by fugo** [comment]
It is resident memory. 
App list:
+ AppMenu
+ Icon Task List
+ Workspace Switcher
+ Places
+ QuickNote
+ Screenshot
+ System Tray
+ Notifications
+ Status Indicator
+ Clock
+ Raven Trigger

with `budgie-panel --replace &!` I get no error messages.
I use nemo-desktop instead of nautilus for desktop icons, but I don't know any other special settings.
I use budgie now for a long time without problems.
How can I debug the memory leak?
Any tips?

**Comment by serebit** [comment]
I can't trigger this to happen on my EndeavourOS install offhand, but I do have something that could help debug the issue. Find the PID for budgie-panel, then run `pmap PID -X` in the terminal, where `PID` is the PID of budgie-panel. **Copy the output to a [Gist](https://gist.github.com/)** and then send the link to that gist here. That tracks virtual memory, not resident memory, but if there are any linked libraries that are using up a ton of virtual memory, we should be able to see them.

**Comment by fugo** [comment]
2 gist files - first after start budgie-panel, the second after > 1h no use.
https://gist.github.com/fugo/86cc2ad3becc3fb8fd94a09826ae97d3
https://gist.github.com/fugo/7930c094f721f224bc7cb7325f66739a

**Comment by serebit** [comment]
Looks like budgie-panel has 940 MB allocated on the *heap* after sitting and doing nothing for over an hour, all of which is in resident memory. Unfortunately, since it's on the heap, the pmap output can't tell us where the leak is (if it is a leak), and we'll need to investigate further. I'll have to look into memory profiling for this.

**Comment by JoshStrobl** [comment]
In the meantime, you could try removing budgie-extras and the respective applets, replacing AppMenu with Budgie Menu. Our default panel layout is `Budgie Menu;Icon Tasklist;Tray;Notifications;Status;User Indicator;Clock;Raven Trigger;`

**Comment by fugo** [comment]
>  `Budgie Menu;Icon Tasklist;Tray;Notifications;Status;User Indicator;Clock;Raven Trigger;`
I tried this now and it looks like one of the additional apps is the reason.
I will add step by step the apps to see when it will happend again.
First with menu, then with screenshot app.

**Comment by fugo** [comment]
Budgie-panel only with screenshot app increase the memory from 42 MB to 71 MB after 6 hours.
This looks like normal behavior. ??

With only App Menu it goes faster up to 300 MB .
So it looks like the Menu is the leak?
But this comes with an update.
Budgie or could this be Gnome also?
With Arch it's living on the edge :smile:

**Comment by fossfreedom** [comment]
Since your observations are about third party applets we will close this issue here. Better discuss these observations with your own budgie community.

**Comment by JoshStrobl** [comment]
Given Arch has no proper Budgie community and this is an issue with a Budgie applet developed by Ubuntu Budgie, I would encourage you @fugo to report your issue to the Ubuntu Budgie budgie-extras Github issue.

Thank you for reporting your issue however and I am happy we were able and to narrow down the issue. As there are no actionable items on our (Buddies of Budgie) part, I am confident this issue is resolved for us and may be passed to a third party.
