### ISSUE TITLE
[Feature Request] Group Favorites (open or closed) in the Icon Task List Applet

### ISSUE THREAD

**Issue by Xmetalfanx** [BuddiesOfBudgie/budgie-desktop#159]
### Current Budgie version

budgie-desktop 10.6.1

### Use-cases

Forgive me if this isn't the correct place for this request as it pertains to an applet, and I am not sure who is behind it ... like if it's an official "budgie team" applet or some third party applet included here in Ubuntu Budgie 22.04 

Anyway the feature would be for the Icon Task List applet, and it's a toggle option to change the default behavor to automatically move favorited/icons items to the left ... "grouping all favorited icons" open or closed ... and then have other open icons to the right of them.

I guess another way to say it is "favorited app/icon grouping" whether that app is open or not 

Example of what i see - 
favorited not open, favorited open, non favorited open, ** non favorited open (clicking favorite/"pin" on this doesn't change the order. (and yes you can move things manually) 

What I am requesting would be for the new favorited app, to be moved to the left, and to be placed after (on the right) of any already existing favorited icons 

This is totally not critical and the overall idea is just to organize the icon task list in the panel more ... nothing more 

### References

Not that I know of but again I am not sure this is the correct place to put this request ... if their was (even non Buddies of Budgie) a specifc applet repo somewhere or even a git repo with say a list of official applets from the "Buddies of Budgie" team, i'd post it there instead.

**Comment by JoshStrobl** [comment]
The IconTasklist applet is an official applet developed by us. My personal opinion is that this may be "feature creep" for the applet, since the sorting by the user can be done already, and anything that isn't sorted would appear on the right / end anyways. This would just create a bunch of extra code and maintenance for a feature that is unlikely to present real-world benefit to a sufficient amount of the user base.

Keeping this open to get the thoughts of @EbonJaeger, @serebit, @guillotjulien, and @fossfreedom at the very least.

**Comment by serebit** [comment]
I'm not necessarily opposed to including this feature, though my enthusiasm is diminished by the fact that this is already sort of how the icon tasklist works. Without explicit manual ordering, favorited app icons will shuffle themselves to the left/start naturally as non-favorited apps are opened and closed. With this in mind, all that would really be necessary is a toggle to "automatically shift newly favorited apps to the left" to accomplish the behavior that you want, rather than enforcing grouping of favorited apps. I'd be fine with adding that toggle.

**Comment by JoshStrobl** [comment]
@serebit The thing is, the person would still need to manually sort them if they want them in a particular order (and not just alphabetical, which we could do but again, added code for not much usage), so at that point they may as well do it anyways without us adding in the automatic shifting to the left.

Another question would be how often are people honestly favoriting and unfavoriting apps that would warrant the opt-in automated behavior? Would they be expecting it to just shift to the left? Sorting? What kind of sorting (alphabetical, frequency, category, if the moon is waxing or waning)?

**Comment by Solarunit** [comment]
>Another question would be how often are people honestly favoriting and unfavoriting apps that would warrant the opt-in automated behavior? Would they be expecting it to just shift to the left? Sorting? What kind of sorting (alphabetical, frequency, category, if the moon is waxing or waning)?

I am just using Icon task list applet only for favorite apps.

![atl text](https://i.imgur.com/gxEObzG.png)

I don't have problem with reordering. The only problem is when I need to add a new app, but it's hidden because `only show favorited` apps are visible, so I have to go to the applet's setting to disable `only show favorited`.

BTW I am also using Task List applet :sunglasses:

**Comment by Xmetalfanx** [comment]
My idea was basically for the automatic sorting though i see and actually agree with the question/issues/ arguments against it ... I honestly wouldn't want anyone to waste too much time adding this (if at all) vs other parts of Budgie, to be honest.... the lack of faving/unfaving thing is totally true as well

**Comment by Xmetalfanx** [comment]
just happened to come back here and not sure how/why but i am seeing the "close issue" button (dont feel like I should since I am not a member of the Buddies of Budgie team) ... My point is that I dont mind this issue being closed but other than the thing I mentioned at the start of this post there, ... I figured other team members may want to weigh in on if it's a good idea and their views on the technical aspect of it for example.

Closing this would also say cut down even just by one, "open issues" for the team to look at

**Comment by JoshStrobl** [comment]
> but i am seeing the "close issue" button (dont feel like I should since I am not a member of the Buddies of Budgie team)

You are able to close your own issues :) But sure, I can close it.
