### ISSUE TITLE
Notification bodies are inconsistent

### ISSUE THREAD

**Issue by EbonJaeger** [BuddiesOfBudgie/budgie-desktop#171]
## Description

Notifications from some programs aren't ellipsized (KDE Connect, web browsers) and wrapped, while others are (`notify-send`). Very long messages could take up the entire height of the screen, and more.

I think this also affects the notifications displayed in Raven.

## Budgie version

budgie-desktop 10.6.2 (git-481817675bc27826a7cf9f39e209a27853fda75b)

## Operating system

Solus 4.3 Fortitude

## Steps to reproduce the issue

1. Go to https://www.bennish.net/web-notifications.html in a web browser
2. Click the Authorize button to allow notifications
3. Click Show

For contrast,
1. In your terminal, run: `notify-send -a Test aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`

## Actual result

![image](https://user-images.githubusercontent.com/5157277/183257020-05cf5681-31d7-457c-955a-fe65a65c1c9c.png)

## Expected result
![image](https://user-images.githubusercontent.com/5157277/183257035-7bad0cc3-e122-40b3-8f40-62f1ac90fc7a.png)

## Additional information
I'm not sure what the Right Thing:tm: to do here even is. Do we want to limit to one line? Two lines? What's the best way to do multiple lines if so?

**Comment by serebit** [comment]
I'd say limit to two lines maximum, and ellipsize the last one.

**Comment by JoshStrobl** [comment]
Two lines is quite small. It's quite handy to be able to read incoming messages that may be multilined. If you can barely read any of the content then what is the point in showing any of it at all? I agree that we need to have some limit.

I think this just comes down to the fact we are using ellipsizing, which will truncate the end when it is character boundaries instead of word boundaries (the aaaaaaaaaa is just one long word, so it falls back to char) and the max_width_chars truncates it to 35 width.

> In the ellipsization process characters are removed from the text in order to make it fit to a given width and replaced with an ellipsis.

https://valadoc.org/pango/Pango.EllipsizeMode.html

See also: Text layout section of https://valadoc.org/gtk+-3.0/Gtk.Label.html

Ideas:

1. Test eliminating max_width_chars and setting `lines` to `6`. If the label causes the notification width to grow, ensure there is a max width set on the width itself.
2. Remove all Pango ellipsizing.
3. Fiddle with the WrapMode
