### ISSUE TITLE
Provide option to explicitly disable Hibernation in power menu

### ISSUE THREAD

**Issue by TheEvilSkeleton** [BuddiesOfBudgie/budgie-desktop#253]
### Current Budgie version

I do not use Budgie.

### Use-cases

Many distributions do not provide support for hibernation. Even worse, some might not even have this feature altogether, for security and longevity reasons of SSDs. Fedora, for example, is among the distributions that do not support, which could affect the upcoming Budgie spin. Having a hibernation button on the power menu at all time could give the impression to the user that this button works as expected and/or is supported by the distribution.

### Proposal

Adding an option that the user and/or distribution can explicitly allow hibernation would help. There could be a warning that the distribution might not provide support for hibernation, while also explaining other risks of hibernation.

### References

This Reddit post that explains the motivation behind Fedora not supporting hibernation: https://www.reddit.com/r/Fedora/comments/r4a4so/interesting_fedora_does_not_support_hibernation/

Image:
![image](https://user-images.githubusercontent.com/50847364/212595153-ff94de81-c8aa-41ec-aacd-23f106fba109.png)

**Comment by serebit** [comment]
Potential way to solve this:

- Add a compile-time option to disable hibernation support entirely (still enabled by default)
- Hide Hibernate option in power dialog by default, and add an option in Budgie Desktop Settings to show it

**Comment by JoshStrobl** [comment]
I would say compile-time option that is on by default, that can be switched off on the Fedora side. I know of folks historically in Solus land that have been known to use hibernation over suspend on their system and I think it would create unnecessary user friction to have it as an option that they would need to go in and enable. Would rather leave it for distributions since they are the ones making configuration and compile-time changes to opt for no-hibernation behavior.

I agree with Fedora's premise, for what it's worth. I exclusively use suspend. But I am not everyone :P

**Comment by JoshStrobl** [comment]
I updated the title to reflect the expected behavior from my side, which is disable versus enable.
