### ISSUE TITLE
Raven notifications/applets mismatch

### ISSUE THREAD

**Issue by ghost** [BuddiesOfBudgie/budgie-desktop#31]
When opening Raven for the first time in a session, it initially shows that the "Applets" section is opened, but what actually appears is "Notifications". Selecting the correct option seems to fix the bug for the remainder of the session, and it defaults back to opening the "notifications" screen from then on.
![Screenshot from 2022-01-09 15-11-10](https://user-images.githubusercontent.com/97410614/148701289-7a927032-4770-407d-a042-e99f7f1f9e92.png)

**Comment by guillotjulien** [comment]
Hi @tyler4tado would it be possible to complete your bug report with details about the OS you are using and the Budgie version you are using?

**Comment by serebit** [comment]
I can confirm that this happens on Solus Budgie, as can @JoshStrobl. This has been known about for a while, but we haven't figured out a way to reliably reproduce it.

**Comment by EbonJaeger** [comment]
The calling code for this is really simple. In the end, it's just calling `main_stack.set_visible_child_name("notifications");` in Raven (main_view.vala), thus setting the visible child of the stack. According to the docs, the stack switcher (the Applets/Notifications buttons in Raven) *should* reflect the visible child on its own (and indeed, there are no methods to set the active stack switcher button). This is looking more like a GTK bug.

**Comment by eddysn0wden** [comment]
I've come to realize this only occurs when launching Raven via the "notifications" (bell) applet, but it works as expected when launching it from the usual "Raven Trigger" (arrow in a box) applet.
_Sorry for ghosting, I genuinely want to help because I have deep appreciation for Budgie, but have personal/mental issues, when I create accounts I have extreme anxiety. Maybe one day I'll overcome this and use my little Intro To IT degree I have and  actually contribute to a project.
Good luck on your endeavors friends, all the best._

**Comment by fossfreedom** [comment]
@EbonJaeger is the get/set visible stuff here relevant  to this issue?

https://stackoverflow.com/questions/22178524/gtk-named-stack-childs

**Comment by EbonJaeger** [comment]
@fossfreedom it looks to me like you just found the solution. The Notification View calls `show_all()` in the constructor, but `show_all()` is *not* called on the main applet view. Adding that call fixes the issue for me. I suspect this might also fix the case where sometimes the Raven trigger doesn't actually open Raven.

PR incoming!
