### ISSUE TITLE
[Bug] Budgie menu headings in a different language

### ISSUE THREAD

**Issue by aquilapl** [BuddiesOfBudgie/budgie-desktop#364]
### Description

In the Budgie menu, the main sections are in English not my native language (polish)

### Budgie version

10.7.1

### Operating System

Solus 4.3 fortitude

### Steps to reproduce the issue

Click menu

### Actual result

![menu](https://user-images.githubusercontent.com/81761491/234530393-f09dff0c-7093-494b-9f92-d8f2b5cdfaa7.png)

### Expected result

All in the native language.

### Additional information

This is my first post on github. If I have filled in anything incorrectly then I apologise in advance.

**Comment by serebit** [comment]
As @fossfreedom said, this is due to the Polish translations being incomplete. If you [join the project on Transifex](https://explore.transifex.com/buddiesofbudgie/budgie-10/) (or you know someone who's fluent in both Polish and English who would be willing to translate), then we'd love to receive some help with getting the rest of the strings translated.
