### ISSUE TITLE
[Request] Adjustable notification pop-up duration

### ISSUE THREAD

**Issue by GiantEnemyCrab** [BuddiesOfBudgie/budgie-desktop#373]
### Budgie version

10.5.2

### Use-cases

Duration of how long notification pop-ups stay could be adjustable in seconds, from 9 second to maybe even infinite (this case, pop-up will stay until the user manually closes).

I think that current duration is easy to miss the pop-up if the user goes away from the screen, and if the "Notifications" Budgie applet is not added to the panel. That is my use-case, because as a user, notifications pop-ups are important, but I haven't added the Notifications applet due to having to clear, etc, even if there is a keyboard shortcut supplied.

### Proposal

One possibility may be that this is a kind of configuration that can be tweaked from dconf-editor, where the user can specify how long the pop-up notification stays in "Seconds" as the unit of time, and allow infinite if the user prefers seeing all the pop-ups until manually closed.

**Comment by serebit** [comment]
I could see the addition of a setting for duration, but adding the ability to keep notifications on screen permanently until they're manually closed kinda wrecks both the notification API that we're using (which allows the sender to define a maximum duration to show on screen) and our current system for persistence. Paging @EbonJaeger for how possible the former would be (making max duration configurable).

**Comment by EbonJaeger** [comment]
Sorry for the delay in putting my thoughts here.

The notification specification says that applications set the expiration timeout when the notification is created, with 0 meaning the notification never expires, and -1 meaning the notification server (us) should decide on a timeout duration.

Currently, we clamp the duration to something we consider sane (some applications set it way too low or way too high), between 6 and 12 seconds.

My concern here is that adding a configuration option to change this will be very confusing to people trying to use it: "hey, I changed this setting and notifications close way earlier than the setting says they should!". There would have to be a very clear description of the setting and what it actually does, which could lead to a few other issues:

- It might require a significant amount of text
- We'd have to figure out how deep we have to go in order to explain it
- We also have to think about translators and how such a description might be translated

Adding a config option for the max duration is doable, but I'm not sure whether it's a direction that we want to go, or of it's the right way to go about it. I'm hesitant to bend the spec any more than we already are.
