### ISSUE TITLE
Keep different instances of an application completely separate in the top bar across workspaces.

### ISSUE THREAD

**Issue by epicsucks** [BuddiesOfBudgie/budgie-desktop#47]
### Current Budgie version

10.5.3

### Use-cases

You want workspaces to act like entirely separate virtual desktops.

### Proposal

Only show the active windows on the current workspace in Icon Task List.
When you click on an icon in Icon Task List it only shows/hides windows in the current workspace.

**Comment by JoshStrobl** [comment]
There is already a "Restrict to workspace" option for Icon Task List. In the event an application is not pinned, it will only show an icon if the app is in the current workspace (when the option is enabled).

Showing all windows across all workspaces in the IconTasklist's Popover is an intentional design decision to facilitate easy window-specific workspace switching and the ability to move them within the panel with a few clicks.
