### ISSUE TITLE
[Bug] Adwaita does not show up in the Widgets menu at all.

### ISSUE THREAD

**Issue by PieyIsAPie** [BuddiesOfBudgie/budgie-desktop#590]
### Description

Adwaita does not show up in the Widgets menu at all. I had to use GNOME tweaks to fix this. After looking through the other issues it seems that Adwaita is blacklisted??? Please fix.

### Budgie version

10.7.1

### Operating System

Debian 12

### Steps to reproduce the issue

Install Adwaita, then go into Budgie Desktop Settings, open the widgets drop down menu, and Adwaita won't be there.

### Actual result

![image](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/83481975/89f226e3-3e0f-4109-b5ce-5d58a91dc73a)

### Expected result

Adwaita to show up.

**Comment by PieyIsAPie** [comment]
Also another thing, when I try to choose arc (The theme you guys suggested) or Fluent, it looks like this
![image](https://github.com/BuddiesOfBudgie/budgie-desktop/assets/83481975/ae6b1b15-9ecd-4d28-bf0d-ae3160e00b98)

**Comment by fossfreedom** [comment]
Adwaita is specifically blocked because this is designed only for GNOME Shell and GNOME specific apps that follow its HIG.

Specific issues about themes should be reported on the theme issue tracker - so for Arc - https://github.com/jnsh/arc-theme

Note - it is likely you have set "dark-theme" or similar via gnome-tweaks.  Again - please avoid using GNOME specific tools for non GNOME-Shell desktop environments - weird results like this could/will occur.
