### ISSUE TITLE
[Bug] Icon Task List — Untranslated tooltip

### ISSUE THREAD

**Issue by Mr-McGregor** [BuddiesOfBudgie/budgie-desktop#633]
### Description

Too bad there's no translation of the applet's tooltip, Budgie's translation has improved over the years...

The easiest thing to do would probably be to remove the 'Launch' verb from /usr/lib/budgie-desktop/plugins/org.budgie-desktop.applet.icon-tasklist/libicontasklistapplet.so, as when  applications are running.

### Budgie version

10.9.2

### Operating System

Solus 4.5

### Steps to reproduce the issue

Hover only over the icon of a 'starred' application in the panel.

### Actual result

![tooltip #1](https://github.com/user-attachments/assets/e8d59d10-e87a-4f01-8097-3c9c7f69d584)
![tooltip #3](https://github.com/user-attachments/assets/b0815445-299b-40d8-9349-58d1bad3dcbe)

### Expected result

![tooltip #2](https://github.com/user-attachments/assets/7db9e4bb-0ad2-443e-9d51-1e318481ee79)

**Comment by fossfreedom** [comment]
This is due to this part of the code in the 10.9.x branch https://github.com/BuddiesOfBudgie/budgie-desktop/blob/3a3ebd379a529a32a39ccfb07591d4b3e1958a7a/src/panel/applets/icon-tasklist/IconButton.vala#L469

In main this whole area has been refactored - "Launch" is no longer used for tooltips.  So this issue will be resolved for a future release of budgie.

**Comment by Mr-McGregor** [comment]
Thanks to both of you!
