### ISSUE TITLE
Applet tooltips are inconsistent (color, position, off-screen, etc)

### ISSUE THREAD

**Issue by 0x199x** [BuddiesOfBudgie/budgie-desktop#71]
## Description
Applet tooltips are very inconsistent. Some are yellow, some are gray, some appear below the panel if configured at the bottom, some are way off off-center.

## Budgie version
10.6

## Operating system
EndeavourOS

## Actual result
https://user-images.githubusercontent.com/89231731/158524270-06b6a6bb-0aef-432d-a732-7375b7a643b2.mp4

## Additional information
Materia theme

**Comment by JoshStrobl** [comment]
The System Tray icons are provided by the application and XEmbed, not Budgie, therefore not our responsibility.

The tooltip issue is a GTK3 bug. @serebit actually had patched it in Solus but since the GNOME folks don't want to merge it and Arch doesn't carry it, not anything we can do about it.

**Comment by serebit** [comment]
To clarify a bit, since the tooltips are provided by the applications and not by Budgie itself, they vary in style—Qt tooltips show up as yellow, and GTK tooltips show up as the color of the system theme. As for positioning (both offscreen and to the side), that's entirely the fault of GTK3, and there's nothing we can do to fix it on our end. [This MR that I made over a year ago](https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/2649) fixes the offscreen ones, but as Josh said, the GNOME folks don't seem to find it enough of a problem to get it merged.

**Comment by 0x199x** [comment]
Ok, thank you for the info.  That makes sense.

Not happy at all with what I've been reading about GNOME lately.  Seems very gatekeep-y as of late.  Your continued efforts on Budgie are very much appreciated.
