### ISSUE TITLE
Can't drag and drop icons on a bar anymore.

### ISSUE THREAD

**Issue by LotteBestGirl** [BuddiesOfBudgie/budgie-desktop#79]
## Description
I can't move the icons on Icons applet anymore, it should be draggable by default but it ins't and I didn't find a single setting that resolved this.

## Budgie version
10.6

## Operating system
Arch Linux, 5.16.15-zen1-1-zen

## Steps to reproduce the issue

- Add the Icon Task List to any bar
- With your mouse, try to drag an icon to ove it

## Actual result
It doens't move.
Here a replica of what happens: https://streamable.com/k4ch9q

## Expected result
It should move the icon to the position I want like it did before.

## Additional information
If I try to move the icon to a browser window for example, it will type out the icon name, like for example: "emacs.desktop".

**Comment by serebit** [comment]
This seems to be a difference from v10.5.3. The reason it used to work is because dragging and dropping apps would pin them to the tasklist automatically, where in v10.6, only apps that are *already* pinned can be moved around in the tasklist. If you want the same behavior, you have to right click the app and click the star to pin it, and then you can drag it around.

I'm not sure if this is a regression or if it's intended, given the commit history for the tasklist, but I'll look into it.

**Comment by serebit** [comment]
Still seeing this on master.
